# Generated by Django 5.2.4 on 2025-08-17 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
        ('userauth', '0002_alter_customer_password_alter_customer_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedproperty',
            name='area_sqft',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='savedproperty',
            name='bedrooms',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='savedproperty',
            unique_together={('user', 'city', 'location')},
        ),
    ]
