# Generated by Django 5.2.4 on 2025-08-17 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_savedproperty_area_sqft_and_more'),
        ('userauth', '0002_alter_customer_password_alter_customer_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResidentialProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('property_type', models.CharField(max_length=100)),
                ('bedrooms', models.IntegerField()),
                ('area_sqft', models.IntegerField()),
                ('seller_name', models.CharField(max_length=100)),
                ('seller_phone', models.CharField(max_length=20)),
                ('property_image', models.URLField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='userauth.customer')),
            ],
        ),
        migrations.DeleteModel(
            name='SavedProperty',
        ),
    ]
