# Generated by Django 5.2.4 on 2025-08-18 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_residentialproperty_delete_savedproperty'),
        ('userauth', '0002_alter_customer_password_alter_customer_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='residentialproperty',
            name='Connectivity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='residentialproperty',
            name='Livability',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='residentialproperty',
            name='Neighbourhood',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='residentialproperty',
            name='Safety',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='residentialproperty',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='residentialproperty',
            name='location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='residentialproperty',
            name='property_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='residentialproperty',
            name='seller_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='residentialproperty',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_properties', to='userauth.customer'),
        ),
    ]
