# Generated by Django 5.2.4 on 2025-08-20 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userauth', '0002_alter_customer_password_alter_customer_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_type', models.CharField(choices=[('Sell', 'Sell'), ('Rent', 'Rent')], max_length=10)),
                ('category', models.CharField(choices=[('Residential', 'Residential'), ('Commercial', 'Commercial')], max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('property_type', models.CharField(max_length=100)),
                ('bedrooms', models.IntegerField(blank=True, null=True)),
                ('bathrooms', models.IntegerField(blank=True, null=True)),
                ('area', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('image', models.URLField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='userauth.customer')),
            ],
        ),
    ]
